<?php
$faIconsArr = array(
	'fa-facebook-official' 		=> 'f230',
	'fa-facebook-square' 		=> 'f082',
	'fa-facebook' 				=> 'f09a',
	'fa-twitter-square'			=> 'f081',
	'fa-twitter'				=> 'f099',
	'fa-linkedin-square'		=> 'f08c',
	'fa-linkedin'				=> 'f0e1',
	'fa-pinterest-square'		=> 'f0d3',
	'fa-pinterest'				=> 'f0d2',
	'fa-pinterest-p'			=> 'f231',
	'fa-google-plus-square'		=> 'f0d4',
	'fa-google-plus'			=> 'f0d5',
	'fa-google-plus-official'	=> 'f2b3',
	'fa-rss'					=> 'f09e',
	'fa-rss-square'				=> 'f143',
	'fa-youtube-square'			=> 'f166',
	'fa-youtube'				=> 'f167',
	'fa-youtube-play'			=> 'f16a',
	'fa-instagram'				=> 'f16d',
	'fa-flickr'					=> 'f16e',
	'fa-tumblr-square'			=> 'f174',
	'fa-tumblr'					=> 'f173',
	'fa-skype'					=> 'f17e',
	'fa-vimeo-square'			=> 'f194',
	'fa-vimeo'					=> 'f27d',
	'fa-reddit-square'			=> 'f1a2',
	'fa-reddit'					=> 'f1a1',
	'fa-reddit-alien'			=> 'f281',
	'fa-houzz'					=> 'f27c',
	'fa-etsy'					=> 'f2d7',
);
?>